variables:
  GIT_STRATEGY: none        # we disable fetch, clone or checkout for every job
  GIT_CHECKOUT: "false"     # as we only want to checkout and fetch in the preperation stage

stages:
  - preperations
  - compile
  - build
  - cook
  - package

preperations:
  stage: preperations
  variables:
    GIT_STRATEGY: fetch
    GIT_CHECKOUT: "true"
  script:
    - call "C:\build-scripts\StartBuild.bat"

compile:
  stage: compile
  script:
    - call "C:\build-scripts\CompileScripts.bat"

build:
  stage: build
  script:
    - call "C:\build-scripts\BuildFiles.bat"

cook:
  stage: cook
  script: 
    - call "C:\build-scripts\CookProject.bat"

package:
  stage: package
  only:
    - web                 # only archive when started through the web interface
    - schedules           # only archive when started at a specific schedule
  script:
    - echo "Adding build to the artifacts"
    - call C:\build-scripts\Archive.bat
  artifacts:
    paths:
      - PenguinGlide.zip
    expire_in: 5 days