var namespace_catch =
[
    [ "Detail", "namespace_catch_1_1_detail.html", "namespace_catch_1_1_detail" ],
    [ "Generators", "namespace_catch_1_1_generators.html", "namespace_catch_1_1_generators" ],
    [ "Matchers", "namespace_catch_1_1_matchers.html", "namespace_catch_1_1_matchers" ],
    [ "always_false", "struct_catch_1_1always__false.html", null ],
    [ "AssertionHandler", "class_catch_1_1_assertion_handler.html", "class_catch_1_1_assertion_handler" ],
    [ "AssertionInfo", "struct_catch_1_1_assertion_info.html", "struct_catch_1_1_assertion_info" ],
    [ "AssertionReaction", "struct_catch_1_1_assertion_reaction.html", "struct_catch_1_1_assertion_reaction" ],
    [ "AutoReg", "struct_catch_1_1_auto_reg.html", "struct_catch_1_1_auto_reg" ],
    [ "BenchmarkLooper", "class_catch_1_1_benchmark_looper.html", "class_catch_1_1_benchmark_looper" ],
    [ "BinaryExpr", "class_catch_1_1_binary_expr.html", "class_catch_1_1_binary_expr" ],
    [ "Capturer", "class_catch_1_1_capturer.html", "class_catch_1_1_capturer" ],
    [ "CaseSensitive", "struct_catch_1_1_case_sensitive.html", "struct_catch_1_1_case_sensitive" ],
    [ "Counts", "struct_catch_1_1_counts.html", "struct_catch_1_1_counts" ],
    [ "Decomposer", "struct_catch_1_1_decomposer.html", "struct_catch_1_1_decomposer" ],
    [ "ExceptionTranslatorRegistrar", "class_catch_1_1_exception_translator_registrar.html", "class_catch_1_1_exception_translator_registrar" ],
    [ "ExprLhs", "class_catch_1_1_expr_lhs.html", "class_catch_1_1_expr_lhs" ],
    [ "GeneratorException", "class_catch_1_1_generator_exception.html", "class_catch_1_1_generator_exception" ],
    [ "IConfig", "struct_catch_1_1_i_config.html", "struct_catch_1_1_i_config" ],
    [ "IContext", "struct_catch_1_1_i_context.html", "struct_catch_1_1_i_context" ],
    [ "IExceptionTranslator", "struct_catch_1_1_i_exception_translator.html", "struct_catch_1_1_i_exception_translator" ],
    [ "IExceptionTranslatorRegistry", "struct_catch_1_1_i_exception_translator_registry.html", "struct_catch_1_1_i_exception_translator_registry" ],
    [ "IGeneratorTracker", "struct_catch_1_1_i_generator_tracker.html", "struct_catch_1_1_i_generator_tracker" ],
    [ "IMutableContext", "struct_catch_1_1_i_mutable_context.html", "struct_catch_1_1_i_mutable_context" ],
    [ "IMutableEnumValuesRegistry", "struct_catch_1_1_i_mutable_enum_values_registry.html", "struct_catch_1_1_i_mutable_enum_values_registry" ],
    [ "IMutableRegistryHub", "struct_catch_1_1_i_mutable_registry_hub.html", "struct_catch_1_1_i_mutable_registry_hub" ],
    [ "IRegistryHub", "struct_catch_1_1_i_registry_hub.html", "struct_catch_1_1_i_registry_hub" ],
    [ "IResultCapture", "struct_catch_1_1_i_result_capture.html", "struct_catch_1_1_i_result_capture" ],
    [ "IRunner", "struct_catch_1_1_i_runner.html", "struct_catch_1_1_i_runner" ],
    [ "is_range", "struct_catch_1_1is__range.html", "struct_catch_1_1is__range" ],
    [ "is_unique", "struct_catch_1_1is__unique.html", null ],
    [ "is_unique< T0, T1, Rest... >", "struct_catch_1_1is__unique_3_01_t0_00_01_t1_00_01_rest_8_8_8_01_4.html", null ],
    [ "IStream", "struct_catch_1_1_i_stream.html", "struct_catch_1_1_i_stream" ],
    [ "ITestCaseRegistry", "struct_catch_1_1_i_test_case_registry.html", "struct_catch_1_1_i_test_case_registry" ],
    [ "ITestInvoker", "struct_catch_1_1_i_test_invoker.html", "struct_catch_1_1_i_test_invoker" ],
    [ "ITransientExpression", "struct_catch_1_1_i_transient_expression.html", "struct_catch_1_1_i_transient_expression" ],
    [ "LazyExpression", "class_catch_1_1_lazy_expression.html", "class_catch_1_1_lazy_expression" ],
    [ "MatchExpr", "class_catch_1_1_match_expr.html", "class_catch_1_1_match_expr" ],
    [ "MessageBuilder", "struct_catch_1_1_message_builder.html", "struct_catch_1_1_message_builder" ],
    [ "MessageInfo", "struct_catch_1_1_message_info.html", "struct_catch_1_1_message_info" ],
    [ "MessageStream", "struct_catch_1_1_message_stream.html", "struct_catch_1_1_message_stream" ],
    [ "NameAndTags", "struct_catch_1_1_name_and_tags.html", "struct_catch_1_1_name_and_tags" ],
    [ "NonCopyable", "class_catch_1_1_non_copyable.html", "class_catch_1_1_non_copyable" ],
    [ "not_this_one", "struct_catch_1_1not__this__one.html", null ],
    [ "pluralise", "struct_catch_1_1pluralise.html", "struct_catch_1_1pluralise" ],
    [ "RegistrarForTagAliases", "struct_catch_1_1_registrar_for_tag_aliases.html", "struct_catch_1_1_registrar_for_tag_aliases" ],
    [ "ResultDisposition", "struct_catch_1_1_result_disposition.html", "struct_catch_1_1_result_disposition" ],
    [ "ResultWas", "struct_catch_1_1_result_was.html", "struct_catch_1_1_result_was" ],
    [ "ReusableStringStream", "class_catch_1_1_reusable_string_stream.html", "class_catch_1_1_reusable_string_stream" ],
    [ "RunTests", "struct_catch_1_1_run_tests.html", "struct_catch_1_1_run_tests" ],
    [ "ScopedMessage", "class_catch_1_1_scoped_message.html", "class_catch_1_1_scoped_message" ],
    [ "Section", "class_catch_1_1_section.html", "class_catch_1_1_section" ],
    [ "SectionEndInfo", "struct_catch_1_1_section_end_info.html", "struct_catch_1_1_section_end_info" ],
    [ "SectionInfo", "struct_catch_1_1_section_info.html", "struct_catch_1_1_section_info" ],
    [ "ShowDurations", "struct_catch_1_1_show_durations.html", "struct_catch_1_1_show_durations" ],
    [ "SourceLineInfo", "struct_catch_1_1_source_line_info.html", "struct_catch_1_1_source_line_info" ],
    [ "StreamEndStop", "struct_catch_1_1_stream_end_stop.html", "struct_catch_1_1_stream_end_stop" ],
    [ "StringMaker", "struct_catch_1_1_string_maker.html", "struct_catch_1_1_string_maker" ],
    [ "StringMaker< bool >", "struct_catch_1_1_string_maker_3_01bool_01_4.html", "struct_catch_1_1_string_maker_3_01bool_01_4" ],
    [ "StringMaker< Catch::Detail::Approx >", "struct_catch_1_1_string_maker_3_01_catch_1_1_detail_1_1_approx_01_4.html", "struct_catch_1_1_string_maker_3_01_catch_1_1_detail_1_1_approx_01_4" ],
    [ "StringMaker< char * >", "struct_catch_1_1_string_maker_3_01char_01_5_01_4.html", "struct_catch_1_1_string_maker_3_01char_01_5_01_4" ],
    [ "StringMaker< char >", "struct_catch_1_1_string_maker_3_01char_01_4.html", "struct_catch_1_1_string_maker_3_01char_01_4" ],
    [ "StringMaker< char const * >", "struct_catch_1_1_string_maker_3_01char_01const_01_5_01_4.html", "struct_catch_1_1_string_maker_3_01char_01const_01_5_01_4" ],
    [ "StringMaker< char[SZ]>", "struct_catch_1_1_string_maker_3_01char[_s_z]_4.html", "struct_catch_1_1_string_maker_3_01char[_s_z]_4" ],
    [ "StringMaker< double >", "struct_catch_1_1_string_maker_3_01double_01_4.html", "struct_catch_1_1_string_maker_3_01double_01_4" ],
    [ "StringMaker< float >", "struct_catch_1_1_string_maker_3_01float_01_4.html", "struct_catch_1_1_string_maker_3_01float_01_4" ],
    [ "StringMaker< int >", "struct_catch_1_1_string_maker_3_01int_01_4.html", "struct_catch_1_1_string_maker_3_01int_01_4" ],
    [ "StringMaker< long >", "struct_catch_1_1_string_maker_3_01long_01_4.html", "struct_catch_1_1_string_maker_3_01long_01_4" ],
    [ "StringMaker< long long >", "struct_catch_1_1_string_maker_3_01long_01long_01_4.html", "struct_catch_1_1_string_maker_3_01long_01long_01_4" ],
    [ "StringMaker< R C::* >", "struct_catch_1_1_string_maker_3_01_r_01_c_1_1_5_01_4.html", "struct_catch_1_1_string_maker_3_01_r_01_c_1_1_5_01_4" ],
    [ "StringMaker< R, typename std::enable_if< is_range< R >::value &&!::Catch::Detail::IsStreamInsertable< R >::value >::type >", "struct_catch_1_1_string_maker_3_01_r_00_01typename_01std_1_1enable__if_3_01is__range_3_01_r_01_4536d8fedfff6d62432b3dc59b56e1380.html", "struct_catch_1_1_string_maker_3_01_r_00_01typename_01std_1_1enable__if_3_01is__range_3_01_r_01_4536d8fedfff6d62432b3dc59b56e1380" ],
    [ "StringMaker< signed char >", "struct_catch_1_1_string_maker_3_01signed_01char_01_4.html", "struct_catch_1_1_string_maker_3_01signed_01char_01_4" ],
    [ "StringMaker< signed char[SZ]>", "struct_catch_1_1_string_maker_3_01signed_01char[_s_z]_4.html", "struct_catch_1_1_string_maker_3_01signed_01char[_s_z]_4" ],
    [ "StringMaker< std::nullptr_t >", "struct_catch_1_1_string_maker_3_01std_1_1nullptr__t_01_4.html", "struct_catch_1_1_string_maker_3_01std_1_1nullptr__t_01_4" ],
    [ "StringMaker< std::string >", "struct_catch_1_1_string_maker_3_01std_1_1string_01_4.html", "struct_catch_1_1_string_maker_3_01std_1_1string_01_4" ],
    [ "StringMaker< std::wstring >", "struct_catch_1_1_string_maker_3_01std_1_1wstring_01_4.html", "struct_catch_1_1_string_maker_3_01std_1_1wstring_01_4" ],
    [ "StringMaker< T * >", "struct_catch_1_1_string_maker_3_01_t_01_5_01_4.html", "struct_catch_1_1_string_maker_3_01_t_01_5_01_4" ],
    [ "StringMaker< T[SZ]>", "struct_catch_1_1_string_maker_3_01_t[_s_z]_4.html", "struct_catch_1_1_string_maker_3_01_t[_s_z]_4" ],
    [ "StringMaker< unsigned char >", "struct_catch_1_1_string_maker_3_01unsigned_01char_01_4.html", "struct_catch_1_1_string_maker_3_01unsigned_01char_01_4" ],
    [ "StringMaker< unsigned char[SZ]>", "struct_catch_1_1_string_maker_3_01unsigned_01char[_s_z]_4.html", "struct_catch_1_1_string_maker_3_01unsigned_01char[_s_z]_4" ],
    [ "StringMaker< unsigned int >", "struct_catch_1_1_string_maker_3_01unsigned_01int_01_4.html", "struct_catch_1_1_string_maker_3_01unsigned_01int_01_4" ],
    [ "StringMaker< unsigned long >", "struct_catch_1_1_string_maker_3_01unsigned_01long_01_4.html", "struct_catch_1_1_string_maker_3_01unsigned_01long_01_4" ],
    [ "StringMaker< unsigned long long >", "struct_catch_1_1_string_maker_3_01unsigned_01long_01long_01_4.html", "struct_catch_1_1_string_maker_3_01unsigned_01long_01long_01_4" ],
    [ "StringMaker< wchar_t * >", "struct_catch_1_1_string_maker_3_01wchar__t_01_5_01_4.html", "struct_catch_1_1_string_maker_3_01wchar__t_01_5_01_4" ],
    [ "StringMaker< wchar_t const * >", "struct_catch_1_1_string_maker_3_01wchar__t_01const_01_5_01_4.html", "struct_catch_1_1_string_maker_3_01wchar__t_01const_01_5_01_4" ],
    [ "StringRef", "class_catch_1_1_string_ref.html", "class_catch_1_1_string_ref" ],
    [ "TestCase", "class_catch_1_1_test_case.html", "class_catch_1_1_test_case" ],
    [ "TestCaseInfo", "struct_catch_1_1_test_case_info.html", "struct_catch_1_1_test_case_info" ],
    [ "TestFailureException", "struct_catch_1_1_test_failure_exception.html", null ],
    [ "TestInvokerAsMethod", "class_catch_1_1_test_invoker_as_method.html", "class_catch_1_1_test_invoker_as_method" ],
    [ "Timer", "class_catch_1_1_timer.html", "class_catch_1_1_timer" ],
    [ "Totals", "struct_catch_1_1_totals.html", "struct_catch_1_1_totals" ],
    [ "UnaryExpr", "class_catch_1_1_unary_expr.html", "class_catch_1_1_unary_expr" ],
    [ "UseColour", "struct_catch_1_1_use_colour.html", "struct_catch_1_1_use_colour" ],
    [ "WaitForKeypress", "struct_catch_1_1_wait_for_keypress.html", "struct_catch_1_1_wait_for_keypress" ],
    [ "WarnAbout", "struct_catch_1_1_warn_about.html", "struct_catch_1_1_warn_about" ]
];